# Generated by Django 6.1.1 on 2026-09-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='confirmation_emails_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Ensures purchase confirmation and invoice emails are dispatched exactly once.'),
        ),
    ]
