databases:
  - name: learnix-postgres
    databaseName: learnix_db
    user: learnix_user
    plan: standard
    region: oregon
    postgresMajorVersion: 16

services:
  - type: web
    name: learnix-app
    runtime: python
    plan: starter
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn learnix_project.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --keep-alive 5 --preload --worker-tmp-dir /dev/shm"
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: learnix-postgres
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: learnix-redis
          type: keyvalue
          property: connectionString
      - key: RENDER_EXTERNAL_HOSTNAME
        value: "learnix-ofqe.onrender.com"
      - key: ALLOWED_HOSTS
        value: "learnix-ofqe.onrender.com,localhost,127.0.0.1"
      - key: RENDER
        value: "true"
      - key: DEFAULT_FROM_EMAIL
        value: "Learnix <shahbazbutt22ee@gmail.com>"
      - key: EMAIL_HOST_USER
        value: "shahbazbutt22ee@gmail.com"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_USE_SSL
        value: "False"
      - key: EMAIL_TIMEOUT
        value: "10"
      - key: STRIPE_CURRENCY
        value: "usd"
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - type: worker
    name: learnix-worker-emails
    runtime: python
    plan: starter
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "celery -A learnix_project worker -Q emails -c 4 --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        fromService:
          name: learnix-app
          type: web
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: learnix-postgres
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: learnix-redis
          type: keyvalue
          property: connectionString

  - type: worker
    name: learnix-worker-docs
    runtime: python
    plan: starter
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "celery -A learnix_project worker -Q documents -c 2 --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        fromService:
          name: learnix-app
          type: web
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: learnix-postgres
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: learnix-redis
          type: keyvalue
          property: connectionString

  - type: worker
    name: learnix-worker-general
    runtime: python
    plan: starter
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "celery -A learnix_project worker -Q default,scheduled -c 2 --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        fromService:
          name: learnix-app
          type: web
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: learnix-postgres
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: learnix-redis
          type: keyvalue
          property: connectionString

  - type: worker
    name: learnix-beat
    runtime: python
    plan: starter
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "celery -A learnix_project beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        fromService:
          name: learnix-app
          type: web
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: learnix-postgres
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: learnix-redis
          type: keyvalue
          property: connectionString

  - type: web
    name: learnix-flower
    runtime: python
    plan: starter
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "celery -A learnix_project flower --basic_auth=$FLOWER_USER:$FLOWER_PASSWORD --address=0.0.0.0 --port=$PORT"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: learnix-redis
          type: keyvalue
          property: connectionString
      - key: FLOWER_USER
        sync: false
      - key: FLOWER_PASSWORD
        sync: false

  - type: keyvalue
    name: learnix-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: []
