# Generated by Django 6.1.1 on 2026-09-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], db_index=True, default='student', help_text='Role distinguishing students from course instructors', max_length=20),
        ),
    ]
