# Generated by Django 6.1.1 on 2026-09-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', help_text='Fallback external URL for demo images', max_length=500),
        ),
    ]
