# Generated by Django 6.1.1 on 2026-09-27 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_thumbnail_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated completion percentage (0.00% to 100.00%)', max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['user', 'course'], name='courses_enr_user_id_eb79d5_idx'), models.Index(fields=['is_active'], name='courses_enr_is_acti_b4e128_idx'), models.Index(fields=['progress_percent'], name='courses_enr_progres_9413ed_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
                'indexes': [models.Index(fields=['user', 'lesson'], name='courses_les_user_id_83b81f_idx'), models.Index(fields=['is_completed'], name='courses_les_is_comp_012467_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
