# Generated by Django 6.1.1 on 2026-09-27 06:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, help_text='Unique verifiable code e.g. LRN-98214-X', max_length=64, unique=True)),
                ('verification_hash', models.CharField(help_text='SHA-256 cryptographic verification ledger hash', max_length=64)),
                ('ceus', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=4)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['certificate_id'], name='courses_cer_certifi_a9a7a7_idx'), models.Index(fields=['user', 'course'], name='courses_cer_user_id_6b0873_idx')],
            },
        ),
    ]
